# image: https://hub.docker.com/r/mautic/mautic/tags
# docs: https://github.com/mautic/docker-mautic


version: '3.8'

services:
  mautic:
    image: mautic/mautic:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - mautic:/var/www/html
    environment:
      # The belows vars is need, otherwise container error
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_USER=${DB_MYSQL_USER}
      - MAUTIC_DB_PASSWORD=${DB_MYSQL_PASSWORD}
      - MAUTIC_DB_NAME=${DB_MYSQL_NAME}
      - MAUTIC_RUN_CRON_JOBS=true
      - MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
      - MAUTIC_RUN_CRON_JOBS=
      - MAUTIC_CRON_HUBSPOT=
      - MAUTIC_CRON_SALESFORCE=
      - MAUTIC_CRON_PIPEDRIVE=
      - MAUTIC_CRON_ZOHO=
      - MAUTIC_CRON_SUGARCRM=
      - MAUTIC_CRON_DYNAMICS=
      - MAUTIC_TESTER=
    links: 
      - mysql
    depends_on:
      - mysql
    restart: always


  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mautic:
  mysql_data: